{{- if .Values.exposedPorts -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluent-bit.fullname" . }}
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
{{ toYaml .Values.exposedPorts | indent 10 }}
  selector:
    app: {{ template "fluent-bit.fullname" . }}
{{- end -}}
